# Usa l'immagine base Node.js
FROM node:18-alpine

# Imposta la directory di lavoro
WORKDIR /app

# Installa 'serve'. Se hai un package.json, puoi spostare 'serve' lì e usare 'npm install'.
RUN npm install -g serve

# Copia i file statici nel container
COPY ./public /app

# Espone la porta 80
EXPOSE 80

# Avvia il server 'serve'. Utilizza '-s' per la modalità single-page application se necessario.
CMD ["serve", "-p", "80", "-s", "."]
