# Usa l'immagine base di Nginx
FROM nginx:alpine

# Rimuovi i file di configurazione di default di Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia i file statici nel container, dentro la directory di Nginx per i contenuti statici
COPY ./public /usr/share/nginx/html

# Esporre la porta 80
EXPOSE 80

# Avvia Nginx e mantienilo in esecuzione in foreground
CMD ["nginx", "-g", "daemon off;"]
